# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: thatnoisykeyboard
email: thatnoisykeyboard@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: 
github_username: 
minimal_mistakes_skin: "default"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Kolkata

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  location : "Kolkata, India"
  name   : "priyanka roy"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : ""
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: ""
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com"
    

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com"
   

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

#repository  : "thatnoisykeyboard/thatnoisykeyboard.github.io"
#comments:
  provider  : "staticman_v2"
  staticman:
    branch    : "master"
staticman_url: https://bananafry.herokuapp.com/v2/entry/sealedhermit/sealedhermit.github.io/master/comments

#reCaptcha:
  siteKey: "6Lf3n7gZAAAAALgkh_9ifByBPLW7BszuGbw5Yy7Z"
  secret: "mX6z+aGbLEY3BEPxLQY37YJ9ll9Qafpcom/+KQAfC/pTxXUhgoXhUg0p1f4fdLLj0y3d/9YjXemjE7agF7J1KrL8xf29bnQleJgFfnV5q6YXpdlfuJqT02zQOuVQwVXImLwmj7EvZJEn/3tpp/jSMBUbGFW8Y7ZOWG9EI0auXnyVWMkISg8H2cVYXcBEYEMOD8zUd5WYQD5geEuGke86borXwWHte8Ese2cBrC6f1IT9jp96q7W5mLyBw3asXsCsMJio0Y7kwOEM2ZO3MnnEmTbeYL/NZCJX4Qp22AOhSEtBh5GpbGa3PkzrmO30N4aJq+2xV8XGDd27o/V7aTsWQw=="

#SEO and Analytics

google_site_verification : "HhY_ZXPdz1S-JQ09ExxaNJxs_FQFKGXvXAXYt0BLpZw"
bing_site_verification   : "7BB8F13E10D9A59C36AC49739A364A41"


#analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-174196763-1"
    anonymize_ip: false # default

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment
